# Site settings
title: Distance Developers Guide
email: distance-sampling@googlegroups.com
project_name: Distance
project_site: http://distancesampling.org/

# gh-pages site subpath
baseurl: /distance-consultancy 
description: Distance Sampling project developer's guide

# GitHub username and repository URL
github_username: DistanceDevelopment
github_url: https://github.com/softwaresaved/distance-consultancy/

# Location of Distance VM scripts
distance_vmscripts: https://github.com/softwaresaved/distance-consultancy/tree/master/vmscripts

# Jekyll settings
theme_name: orderedlist
theme_url: https://github.com/orderedlist

# Build settings
markdown: kramdown
exclude: [internal]
